# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-27 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='Please add a description of this book.'),
            preserve_default=False,
        ),
    ]
